### ISSUE TITLE
Incorrect python binary used when launching as an executable script in a virtualenv

### ISSUE THREAD

**Issue by u0m3** [SySS-Research/outis#1]
Here is the output from shell
```
root@kali:~# workon outis
(outis) root@kali:~# cd Documents/outis/
(outis) root@kali:~/Documents/outis# ./outis.py 
Traceback (most recent call last):
  File "./outis.py", line 2, in <module>
    from syhandler.handler import Handler
  File "/root/Documents/outis/syhandler/handler.py", line 13, in <module>
    from syplatform.powershell.powershell import PlatformPowershell
  File "/root/Documents/outis/syplatform/powershell/powershell.py", line 3, in <module>
    import syhelpers.strings as helps
  File "/root/Documents/outis/syhelpers/strings.py", line 5, in <module>
    from Crypto.Random import random
ImportError: No module named 'Crypto'
(outis) root@kali:~/Documents/outis# which python3
/root/.virtualenvs/outis/bin/python3
(outis) root@kali:~/Documents/outis# python3 outis.py 
outis>
```

The simple fix (in my humble opinion) would be to change
```python
#!/usr/bin/python3
```
to
```python
#!/usr/bin/env python3
```

**Comment by mdeeg** [comment]
Thanks for reporting this issue. I have just fixed the shebang line of outis.py.
